name: learning_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: yjxm188 <email@example.com>

environment:
  sdk: '<=2.2.0'
  quiver: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ^2.0.3

dev_dependencies:
  test: ^1.6.2
